remove redundant validation checks
Chia-Network/bls-signatures pull request #196
Opened 2021-03-31 06:36 UTC by arvidn

`ep_map_dst()` and `ep2_map_dst()` ought to return valid points, the validation of their output is redundant (and expensive).

These are my timings before and after this change:

```
Batch verification
Total: 100000 runs in 133637 ms
Avg: 1.33637 ms
```

```
Batch verification
Total: 100000 runs in 73739 ms
Avg: 0.73739 ms
```

2021-03-31 06:39 UTC, arvidn commented
@xdustinface is the premise for this change correct?

2021-03-31 06:46 UTC, mariano54 approved these changes

2021-03-31 06:49 UTC, arvidn commented on src/elements.cpp
>      bn_free(order);
as a bonus, `order` would leak if the check failed previously.

2021-03-31 06:57 UTC, wjblanke approved these changes
looks ok, as long as they are good!

2021-04-01 00:09 UTC, xdustinface requested changes
> @xdustinface is the premise for this change correct?

I think it makes sense 👍 But i have two points:

- If this will be merged there should probably still be a `BLS::CheckRelicErrors()` call where you removed the subgroup checks.
- I looked into the related relic parts a bit and im not sure how to interpret and weight [this comment](https://github.com/relic-toolkit/relic/blob/main/src/ep/relic_ep_map.c#L155-L159). Can it fail or not? 🤔 And if it fails, does it then silently end up in the wrong group (which would be a breaker for this PR) or will it throw? I guess this should be answered first but i probably can't with certainty 🙈

2021-04-01 08:11 UTC, arvidn commented
> If this will be merged there should probably still be a `BLS::CheckRelicErrors()` call where you removed the subgroup checks.

I agree. I added those checks back.

> I looked into the related relic parts a bit and im not sure how to interpret and weight [this comment](https://github.com/relic-toolkit/relic/blob/main/src/ep/relic_ep_map.c#L155-L159). Can it fail or not? :thinking: And if it fails, does it then silently end up in the wrong group (which would be a breaker for this PR) or will it throw? I guess this should be answered first but i probably can't with certainty :see_no_evil:

@dfaranha or @kwantam could you comment on the assumption that `ep_map_dst()` and `ep2_map_dst()` always either:

* return valid points in the G1 and G2 subgroups respectively
* fail and set the error code in `core_get()->code`.

2021-04-01 18:11 UTC, dfaranha commented
From @kwantam

2021-04-01 18:23 UTC, arvidn commented
> PS: I have implemented faster subgroup checks (in a80e1db252c78854b1017a8fc97e6b962502031d) as per (https://eprint.iacr.org/2019/814.pdf). Does the benchmarking here reflect this? Not sure about which version was measured.

I noticed that yesterday. This benchmark is running against an older version of relic, and we do our own subgroup check as well.
I have a patch ready locally that bumps the relic dependency and removes our own subgroup check.

2021-04-01 19:01 UTC, merged