feat: implement memory-copy only of G1Element and G2Element
Chia-Network/bls-signatures pull request #364
Opened 2023-04-21 19:21 UTC by PastaPastaPasta

This implements a performant memory-only copy for G1Element and G2Element; I don't have benchmarks, but when we used this we saw significant performance improvements.

2023-04-24 01:49 UTC, hoffmang9 commented
Now that we've completed some needed housekeeping, could you rebase so we can get a clean CI and get this in?

Thanks very much for your upstream!

-Gene

2023-05-08 17:31 UTC, arvidn requested changes

2023-05-08 17:31 UTC, arvidn commented on src/elements.hpp
> +    G1Element Copy();
in C++, this functionality is implemented by copy constructors. I can't see a good reason to have this be a member function instead. But, if there is a good reason, it should *at least* be a `const` member function

2023-06-15 20:42 UTC, emlowe commented
Closing PR - this isn't required due to the implicit C++ copy constructors, which are already in memory (essentially a memcpy)

2023-06-15 20:42 UTC, closed without merging