Division operator for GTElement (e1/e2)
Chia-Network/bls-signatures pull request #438
Opened 2023-10-25 18:28 UTC by kofi-dalvik

Currently creating a [witness encryption scheme](https://github.com/kofi-dalvik/bls-witness-encryption) based on BLS signatures. I am using this library. However, I needed the GTElement class to support inversing through divisions. Instead of reimplementing element classes (since r is private in GT), this PR fixed the issue. 

I know BLS signature implementation does not use division, but libraries that depend on this might need it. Moreover, my witness encryption library currently depends on my fork, and I want to use the main Chia-Network/bls-signatures instead.

2023-11-07 22:33 UTC, hoffmang9 approved these changes
Thanks for your contribution

2023-11-07 22:34 UTC, hoffmang9 commented
Can you sign your commit?

2023-11-10 00:58 UTC, kofi-dalvik commented
Thanks @hoffmang9 , 
Signed now

2023-11-10 01:00 UTC, hoffmang9 commented
<img width="491" alt="image" src="https://github.com/Chia-Network/bls-signatures/assets/30377676/71b36a9c-0f41-4e8b-be04-ab959298e2a7">
Looks like something is still a bit off.

2023-11-10 01:04 UTC, kofi-dalvik commented
> <img alt="image" width="491" src="https://user-images.githubusercontent.com/30377676/281922004-71b36a9c-0f41-4e8b-be04-ab959298e2a7.png"> Looks like something is still a bit off.

Yeah i noticed and I'm resolving it. Used a different email for this repository

2024-05-13 22:45 UTC, emlowe commented
Apologies for the long delay in looking at this. But I have a question. The included test is odd since division is not normally commutative - so one doesn't expect a test where `a/b == b/a`

I would expect something like `(a*b)/b == a` - does this version of division pass that test?

2024-05-16 00:58 UTC, kofi-dalvik commented
Hi @emlowe thanks for this message. In fact, I forgot about this PR. 

Your observation is correct, which would be a more precise test. The current test works because gt1 and gt2 are both GT generators and are the same. It will make more sense that gt1 and gt2 are different elements. I'll update the test.

2024-10-18 16:04 UTC, emlowe requested changes
I'm not sure it's correct to call "multiplication of the inverse" a division operation

2025-03-03 18:13 UTC, emlowe commented
closing PR

2025-03-03 18:13 UTC, closed without merging